version: '3.9'
services:
  web:
    build: 
      context: ./ShopGen
    ports:
      - '61445:80'
  api:
    build:
      context: ./ShopGen.API
    ports:
      - '61122:61122'
    volumes:
      - 'tmdevdata01:/data/shop-gen/img'

networks:
  default:
    external: true
    name: tmdevnet01

volumes:
  tmdevdata01:
    external: true